import os

base = os.environ.get('URL')

URLS = {
    'About Our Ads': f'{base}/aboutourads',
    'About Us': f'{base}/about-us',
    'Adblock FAQ': f'{base}/adblock-faq',
    'Algebra Lessons': 'https://www.coolmath.com/algebra',
    'Base Ten Blocks Manipulative': 'https://www.coolmath4kids.com/manipulatives/base-ten-blocks',
    'Blog': f'{base}/blog',
    'CONTACT US': f'{base}/contact-us',
    'Classic Games': f'{base}/1-classic-games',
    'Coolmath4Kids': 'https://www.coolmath4kids.com/',
    'Coolmath4Parents': 'http://www.coolmath4parents.com/',
    'Coolmath4Teachers': 'http://www.coolmath4teachers.com/',
    'Decimals': 'https://www.coolmath.com/prealgebra/02-decimals',
    'Facebook': 'https://www.facebook.com/CoolMathGamesLLC',
    'Factors and Primes': 'https://www.coolmath.com/prealgebra/00-factors-primes',
    'Geography Games': f'{base}/1-geography-games',
    'Instagram': 'https://www.instagram.com/coolmathgames/',
    'Jigsaw Puzzles': f'{base}/0-jigsaw-puzzles',
    'Lines': 'https://www.coolmath.com/algebra/08-lines',
    'Logic Games': f'{base}/1-logic-games',
    'Math Dictionary': 'https://coolmath.com/reference/online-math-dictionary',
    'Math Quizzes': 'https://www.coolmath4kids.com/quizzes',
    'Memory Games': f'{base}/1-memory-games',
    'Number Games': f'{base}/1-number-games',
    'Number Line Manipulative': 'https://www.coolmath4kids.com/manipulatives/number-line',
    'Pattern Blocks Manipulative': 'https://www.coolmath4kids.com/manipulatives/pattern-blocks',
    'Pre-Algebra Lessons': 'https://www.coolmath.com/prealgebra',
    'Pre-Calculus Lessons': 'https://www.coolmath.com/precalculus-review-calculus-intro',
    'Properties': 'https://www.coolmath.com/prealgebra/06-properties',
    'Science Games': f'{base}/1-science-games',
    'Skill Games': f'{base}/1-skill-games',
    'Strategy Games': f'{base}/1-strategy-games',
    'Subscription FAQ': f'{base}/subscription-faq',
    'Subscription Support': f'{base}/contact-us-about-subscriptions',
    'Ten Frame Manipulative': 'https://www.coolmath4kids.com/manipulatives/ten-frame',
    'Terms of Use': f'{base}/terms-use',
    'Twitter': 'https://twitter.com/TheRealCoolmath',
    'SUGGEST A GAME': f'{base}/suggest-a-game',
    'SUBMIT A GAME': f'{base}/submit-a-game',
    'COOLMATH GAMES PRIVACY POLICY': f'{base}/privacyp',
}
